### ISSUE TITLE
Prevents schematics from being placed in the world

### ISSUE THREAD

**Issue by WickedSchnitzel** [DArkHekRoMaNT/CommonLib#5]
### Mod Version

1.0

### CommonLib Version

1.9.0

### Game Version

1.19.1 stable

### OS

Windows

### Play mode

Multiplayer

### Problem

Prevents schematics from being placed in the world on chunk generation. Cannot be used on servers that are using custom schematics atm.

### Logs

```bash
[Server Error] [game] Exception: Object reference not set to an instance of an object.
   at Tavis.JsonPointer..ctor(String pointer)
   at Vintagestory.ServerMods.NoObf.ModJsonPatchLoader.ApplyPatch(Int32 patchIndex, AssetLocation patchSourcefile, JsonPatch jsonPatch, Int32& applied, Int32& notFound, Int32& errorCount) in VSEssentials\Loading\JsonPatchLoader.cs:line 270
   at Vintagestory.ServerMods.NoObf.ModJsonPatchLoader.AssetsLoaded(ICoreAPI api) in VSEssentials\Loading\JsonPatchLoader.cs:line 157
   at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 626
```

**Comment by DArkHekRoMaNT** [comment]
What schematics are you talking about? And how does this relate to CommonLib? o.O

**Comment by WickedSchnitzel** [comment]
> What schematics are you talking about? And how does this relate to CommonLib? o.O

I just checked again. Seems to happen only in conjunction with "Capture Animals". Then that error will occur and custom schematics like new ruins that should be patched into the world will just not spawn at all.

**Comment by WickedSchnitzel** [comment]
At least it happens with our server pack, not sure about other mods that are using custom schematics. I just remembered that we have patched that mod, so it may somehow have to do with it, i need to test this later after work.
[addbaits.json](https://github.com/DArkHekRoMaNT/CommonLib/files/14009067/addbaits.json)

**Comment by DArkHekRoMaNT** [comment]
> At least it happens with our server pack, not sure about other mods that are using custom schematics. I just remembered that we have patched that mod, so it may somehow have to do with it, i need to test this later after work. [addbaits.json](https://github.com/DArkHekRoMaNT/CommonLib/files/14009067/addbaits.json)

Tavis is the patch library that the game uses. There may be some mistake in the patch, but at first glance I don't see any problems. More logs (server-main.txt and server-debug.txt) would be useful
