### ISSUE TITLE
CommonLib mod fails to load in certain conditions

### ISSUE THREAD

**Issue by BillyGalbreath** [DArkHekRoMaNT/CommonLib#7]
### Mod Version
2.3.0 - 2.3.7 (maybe older, too)

### CommonLib Version
see above

### Game Version
1.18.8-1.19.7

### OS
Windows, Linux

### Play mode
Multiplayer

### Problem
When connecting to a server that does not have CommonLib installed, the mod fails to load on the client.

### Reproduction steps:
1) setup vanilla server (no mods)
2) add CommonLib to the client
3) add any mod that requires CommonLib to the client (I used [Extra Overlays](https://mods.vintagestory.at/extraoverlays))
4) connect client to the vanilla server and witness no overlays

### Analysis
I believe this happens because the mod defaults to `universal` side with both client and server being required in the `modinfo.json` file.

### Solution
The problem is fixed when I edit `modinfo.json` to tell it the server is __not__ required. The defaults of universal side and client required are still in effect.
```json
"requiredOnServer": false
```

Note: I left side as universal and client as required so that it still behaves as expected in every scenario. Servers will still tell clients it is required if it is installed on servers. This change just makes it so client can run it without it also being on the server.

### Logs
Client log has these errors (not on startup, only when connecting to the server):
```bash
...
2.5.2024 15:20:49 [Client Notification] Found 5 mods (1 disabled)
2.5.2024 15:20:49 [Client Error] [extraoverlays] Could not resolve some dependencies:
2.5.2024 15:20:49 [Client Error] [extraoverlays]     commonlib@2.3.0 - Missing
2.5.2024 15:20:49 [Client Notification] Mods, sorted by dependency: game, creative, survival, extraoverlays
...
2.5.2024 15:20:55 [Client Warning] ===============================================================
2.5.2024 15:20:55 [Client Warning] (x_x) Captured 2 issues during startup:
2.5.2024 15:20:55 [Client Error] [extraoverlays] Could not resolve some dependencies:
2.5.2024 15:20:55 [Client Error] [extraoverlays]     commonlib@2.3.0 - Missing
2.5.2024 15:20:55 [Client Warning] ===============================================================
...
```

### Mods
```bash
Extra Overlays v1.4.0
```

### Screenshots
n/a

**Comment by DArkHekRoMaNT** [comment]
Will this really work now? I've already tried adding requiredOn* twice to fix this problem, but it only ended up causing more problems. For example, the lib was not downloaded for other Universal mods

**Comment by DArkHekRoMaNT** [comment]
I'll try this. Hopefully if it's only RequiredOnServer: false it will work correctly
